:- houses(Houses),exists(house(english,,,,red),Houses),
exists(house(spanish,dog,,,),Houses),
exists(house(,,,coffee,green),Houses),
exists(house(ukranian,,,tea,),Houses),
rightOf(house(,,,,green),house(,,,,ivory),Houses),
exists(house(,snail,oldgold,,),Houses),
exists(house(,,kools,,yellow),Houses),
middleHouse(house(,,,milk,),Houses),
firstHouse(house(norwegian,,,,),Houses),
nextTo(house(,,chesterfields,,),house(,fox,,,),Houses),
nextTo(house(,,kools,,),house(,horse,,,),Houses),
exists(house(,,luckystrike,orangejuice,),Houses),
exists(house(japanese,,parliaments,,),Houses),
nextTo(house(norwegian,,,,),house(,,,,blue),Houses),
exists(house(WaterDrinker,,,water,),Houses),
exists(house(ZebraOwner,zebra,,,),Houses),
write(‘WaterDrinker = ’), 
write(WaterDrinker), nl,write(‘ZebraOwner = ’), write(ZebraOwner),
nl,
write(Houses).
